---
title: "In-class Exercise 5"
author: "Kenneth Yong"
---

# Getting Started

```{r}
pacman::p_load(tidyverse, readxl, SmartEDA, easystats, gtsummary)
```

# Importing Data

```{r}
car_resale <- read_xls("data/ToyotaCorolla.xls", "data")
```

```{r}
summary(car_resale)
```

```{r}
glimpse(car_resale)
```
```{r}
list(car_resale)
```

# Data Overview

```{r}
car_resale %>%
  ExpData(type = 1)
```

```{r}
car_resale %>%
  ExpData(type = 2)
```

# Recoding

```{r}
cols <- c("Mfg_Month",
"HP_Bin",
"CC_bin",
"Doors",
"Gears",
"Cylinders",
"Fuel_Type",
"Color",
"Met_Color",
"Automatic",
"Mfr_Guarantee",
"BOVAG_Guarantee",
"ABS",
"Airbag_1",
"Airbag_2",
"Airco",
"Automatic_airco",
"Boardcomputer",
"CD_Player",
"Central_Lock",
"Powered_Windows",
"Power_Steering",
"Radio",
"Mistlamps",
"Sport_Model",
"Backseat_Divider",
"Metallic_Rim",
"Radio_cassette",
"Tow_Bar"
)

car_resale <- read_xls("data/ToyotaCorolla.xls",
                       sheet = "data") %>%
  mutate(Id = as.character(Id)) %>%
  mutate_each_(funs(factor(.)),cols)
```

# Data Visualisation

```{r}
car_resale %>% 
  ExpNumViz(target=NULL,
            nlim=10,
            Page=c(2,2))
```

```{r}
car_resale %>% 
  ExpNumViz(target="Price",
            nlim=10,
            Page=c(2,2))
```

```{r}
#| fig-width: 12
#| fig-height: 10
car_resale %>%
  ExpCatViz(target=NULL,
            col = "sky blue",
            clim=10,
            margin=2,
            Page = c(4,4),
            sample=16)
```

## Regression Model

```{r}
model <- lm(Price ~ Age_08_04 + Mfg_Year + KM +
              Weight + Guarantee_Period, data = car_resale)
model
plot(model)
```
## Check for multicollinearity

```{r}
check_collinearity(model)
```

```{r}
check_c <- check_collinearity(model)
plot(check_c)
```
## Check for normality

```{r}
model1 <- lm(Price ~ Age_08_04 + KM +
              Weight + Guarantee_Period, data = car_resale)
checkn <- check_normality(model1)
checkn
plot(checkn)
```

## Check for heteroscedasticity

```{r}
checkh <- check_heteroscedasticity(model1)
checkh
plot(checkh)
```